apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tes
    aadpodidbinding: {{ .Values.identity.name }}
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tes
        aadpodidbinding: {{ .Values.identity.name }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/tes: runtime/default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [1000]
      terminationGracePeriodSeconds: 90
      containers:
        - env:
            - name: TesPostgreSql__ServerName
              value: {{ .Values.tesDatabase.serverName }}
            - name: TesPostgreSql__ServerNameSuffix
              value: {{ .Values.tesDatabase.serverNameSuffix }}
            - name: TesPostgreSql__ServerSslMode
              value: {{ .Values.tesDatabase.serverSslMode }}
            - name: TesPostgreSql__ServerPort
              value: {{ .Values.tesDatabase.serverPort | quote }}
            - name: TesPostgreSql__DatabaseName
              value: {{ .Values.tesDatabase.databaseName }}
            - name: TesPostgreSql__DatabaseUserLogin
              value: {{ .Values.tesDatabase.databaseUserLogin }}
            - name: TesPostgreSql__DatabaseUserPassword
              value: {{ .Values.tesDatabase.databaseUserPassword }}
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:{{ .Values.service.tesPort }}/
            - name: Storage__DefaultAccountName
              value: {{ .Values.persistence.storageAccount }}
            - name: AzureServicesAuthConnectionString
              value: {{ .Values.config.azureServicesAuthConnectionString }}
            - name: ApplicationInsights__AccountName
              value: {{ .Values.config.applicationInsightsAccountName }}
            - name: AzureOfferDurableId
              value: {{ .Values.config.azureOfferDurableId }}
            - name: BatchScheduling__UseLegacyAutopools
              value: {{ .Values.config.batchScheduling.useLegacyAutopools | quote }}
            - name: BatchAccount__AccountName
              value: {{ .Values.config.batchAccount.accountName }}
            - name: BatchNodes__SubnetId
              value: {{ .Values.config.batchNodes.subnetId }}
            - name: BatchNodes__DisablePublicIpAddress
              value: {{ .Values.config.batchNodes.disablePublicIpAddress | quote }}
            - name: BatchScheduling__Disable
              value: {{ .Values.config.batchScheduling.disable | quote }}
            - name: NodeImages__Docker
              value: {{ .Values.config.nodeImages.docker }}
            - name: BatchImageGen2__Offer
              value: {{ .Values.config.batchImageGen2.offer }}
            - name: BatchImageGen2__Publisher
              value: {{ .Values.config.batchImageGen2.publisher }}
            - name: BatchImageGen2__Sku
              value: {{ .Values.config.batchImageGen2.sku | quote }}
            - name: BatchImageGen2__Version
              value: {{ .Values.config.batchImageGen2.version }}
            - name: BatchImageGen2__NodeAgentSkuId
              value: {{ .Values.config.batchImageGen2.nodeAgentSkuId }}
            - name: BatchImageGen1__Offer
              value: {{ .Values.config.batchImageGen1.offer }}
            - name: BatchImageGen1__Publisher
              value: {{ .Values.config.batchImageGen1.publisher }}
            - name: BatchImageGen1__Sku
              value: {{ .Values.config.batchImageGen1.sku | quote }}
            - name: BatchImageGen1__Version
              value: {{ .Values.config.batchImageGen1.version }}
            - name: BatchImageGen1__NodeAgentSkuId
              value: {{ .Values.config.batchImageGen1.nodeAgentSkuId }}
            - name: BatchScheduling__PoolRotationForcedDays
              value: {{ .Values.config.batchScheduling.poolRotationForcedDays | quote }}
            - name: BatchScheduling__Prefix
              value: {{ .Values.config.batchScheduling.prefix | quote }}
            - name: Martha__Url
              value: {{ .Values.config.martha.url }}
            - name: Martha__KeyVaultName
              value: {{ .Values.config.martha.keyVaultName }}
            - name: Martha__SecretName
              value: {{ .Values.config.martha.secretName }}
            - name: BatchScheduling__UsePreemptibleVmsOnly
              value: {{ .Values.config.batchScheduling.usePreemptibleVmsOnly | quote}}
            - name: BatchNodes__GlobalStartTask
              value: {{ .Values.config.batchNodes.globalStartTask }}
            - name: BatchNodes__GlobalManagedIdentity
              value: {{ .Values.config.batchNodes.globalManagedIdentity }}
            - name: Storage__ExternalStorageContainers
{{- $containers  := list -}}
{{- range .Values.externalSasContainers }}
{{- $containers = append $containers (printf "https://%s.blob.core.windows.net/%s?%s" .accountName .containerName .sasToken) -}}
{{- end }}
              value: {{ join ";" $containers}}
          image: {{ .Values.images.tes }}
          name: tes
          ports:
            - containerPort: {{ .Values.service.tesPort }}
          resources:
            requests:
              cpu: "1.5"
              memory: "3072Mi"
            limits:
              cpu: "8.0"
              memory: "8192Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
status: {}
