apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tes
    aadpodidbinding: {{ .Values.identity.name }}
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tes
        aadpodidbinding: {{ .Values.identity.name }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:{{ .Values.service.tesPort }}/
            - name: DefaultStorageAccountName
              value: {{ .Values.persistence.storageAccount }}
            - name: AzureServicesAuthConnectionString
              value: {{ .Values.config.azureServicesAuthConnectionString }}
            - name: ApplicationInsightsAccountName
              value: {{ .Values.config.applicationInsightsAccountName }}
            - name: CosmosDbAccountName
              value: {{ .Values.config.cosmosDbAccountName }}
            - name: AzureOfferDurableId
              value: {{ .Values.config.azureOfferDurableId }}
            - name: BatchAccountName
              value: {{ .Values.config.batchAccountName }}
            - name: BatchNodesSubnetId
              value: {{ .Values.config.batchNodesSubnetId }}
            - name: BlobxferImageName
              value: {{ .Values.config.blobxferImageName }}
            - name: DisableBatchNodesPublicIpAddress
              value: {{ .Values.config.disableBatchNodesPublicIpAddress | quote }}
            - name: DisableBatchScheduling
              value: {{ .Values.config.disableBatchScheduling | quote }}
            - name: DockerInDockerImageName
              value: {{ .Values.config.dockerInDockerImageName }}
            - name: UseLegacyBatchImplementationWithAutopools
              value: {{ .Values.config.useLegacyBatchImplementationWithAutopools | quote }}
            - name: BatchImageOffer
              value: {{ .Values.config.batchImageOffer }}
            - name: BatchImagePublisher
              value: {{ .Values.config.batchImagePublisher }}
            - name: BatchImageSku
              value: {{ .Values.config.batchImageSku }}
            - name: BatchImageVersion
              value: {{ .Values.config.batchImageVersion }}
            - name: BatchNodeAgentSkuId
              value: {{ .Values.config.batchNodeAgentSkuId }}
            - name: BatchPoolRotationForcedDays
              value: {{ .Values.config.batchPoolRotationForcedDays | quote }}
            - name: Name
              value: {{ .Values.config.name }}
            - name: MarthaUrl
              value: {{ .Values.config.marthaUrl }}
            - name: MarthaKeyVaultName
              value: {{ .Values.config.marthaKeyVaultName }}
            - name: MarthaSecretName
              value: {{ .Values.config.marthaSecretName }}
            - name: UsePreemptibleVmsOnly
              value: {{ .Values.config.usePreemptibleVmsOnly | quote}}
            - name: ExternalStorageContainers
{{- $containers  := list -}}
{{- range .Values.externalSasContainers }}
{{- $containers = append $containers (printf "https://%s.blob.core.windows.net/%s?%s" .accountName .containerName .sasToken) -}}
{{- end }}
              value: {{ join ";" $containers}}
          image: {{ .Values.images.tes }}
          name: tes
          ports:
            - containerPort: {{ .Values.service.tesPort }}
          resources: {}
          volumeMounts:
{{- range .Values.defaultContainers }}
            - mountPath: {{.}}
              name: {{.}}-claim1
{{- end }}
{{- range .Values.externalContainers }}
            - mountPath: /{{.accountName}}/{{.containerName}}
              name: {{.accountName}}-{{.containerName}}-claim1
{{- end }}
{{- range .Values.externalSasContainers }}
            - mountPath: /{{.accountName}}/{{.containerName}}
              name: {{.accountName}}-{{.containerName}}-claim1
{{- end }}
      restartPolicy: Always
      volumes:
{{- range .Values.defaultContainers }}
        - name: {{.}}-claim1
          persistentVolumeClaim:
            claimName: {{.}}-claim1
{{- end }}
{{- range .Values.externalContainers }}
        - name: {{.accountName}}-{{.containerName}}-claim1
          persistentVolumeClaim:
            claimName: {{.accountName}}-{{.containerName}}-claim1
{{- end }}
{{- range .Values.externalSasContainers }}
        - name: {{.accountName}}-{{.containerName}}-claim1
          persistentVolumeClaim:
            claimName: {{.accountName}}-{{.containerName}}-claim1
{{- end }}
status: {}
